[model_deepseek]
provider   = "azure_deepseek"
endpoint   = "[URL]"
api_key    = "[API_KEY]"
model_name = "DeepSeek-R1"
[model_o3]
provider = "2024-12-01-preview"
endpoint    = "[URL]"
api_key     = "[API_KEY]"
deployment  = "o3-mini"
model_name = "o3-mini"
[varsfile]
path = "config/variables.json"
[directives]
path = "config/directrices.txt"

